Bump sdk to v1.3
opsmill/nornir-infrahub pull request #34
Opened 2024-12-31 10:50 UTC by BaptisteGi

2025-01-06 14:53 UTC, FragmentedPacket commented on pyproject.toml
> +setuptools = "^75.7.0"
Is this added to work with Python 3.12?

2025-01-07 10:04 UTC, BaptisteGi commented on pyproject.toml
> +setuptools = "^75.7.0"
I think all versions of python were impacted here. From my understanding it's pytest that needs a module called `pkg_resources` to work: https://github.com/opsmill/nornir-infrahub/actions/runs/12631013053/job/35191943359\

(and `pkg_resources` is part of setuptools)

2025-01-08 15:52 UTC, FragmentedPacket approved these changes

2025-01-08 22:01 UTC, wvandeun requested changes

2025-01-08 22:01 UTC, wvandeun commented on nornir_infrahub/plugins/inventory/infrahub.py
> +from infrahub_sdk.schema import NodeSchemaAPI
Doing this change, means we have to update the min version of the infrahub-sdk dependency.
Also we'll need to make a release and therefor bump the package version.

2025-01-08 22:02 UTC, wvandeun commented on nornir_infrahub/plugins/tasks/artifact.py
> +        kind="CoreArtifact", definition__artifact_name__value=artifact, object__ids=[node.id]
What is the reason behind this change?

2025-01-08 22:16 UTC, FragmentedPacket commented on nornir_infrahub/plugins/tasks/artifact.py
> +        kind="CoreArtifact", definition__artifact_name__value=artifact, object__ids=[node.id]
We're passing in the name of the artifact definition, at least in our example. I may have made this change hastily, and I should have updated the `examples/nornir_tasks.py` to pass in the artifact name rather than the artifact definition name.

2025-01-09 09:20 UTC, wvandeun commented on nornir_infrahub/plugins/tasks/artifact.py
> +        kind="CoreArtifact", definition__artifact_name__value=artifact, object__ids=[node.id]
We can change the behavior for sure if that is desirable, but this would be a breaking change that we need to communicate properly

2025-01-09 09:26 UTC, wvandeun commented
@FragmentedPacket  not sure about the try/except logic. We would need to this everywhere we do that import (tests) as well. Maybe we should just set the min version of the SDK. 

I think, for now this should be ok. I don't think we want to maintain to much of a backwards compatibility anyway. Things are still changing quite a bit anyway. So this shouldn't be to big of a problem.

2025-01-09 13:41 UTC, wvandeun approved these changes

2025-01-09 14:30 UTC, FragmentedPacket approved these changes

2025-01-09 21:13 UTC, merged